#cloud-config

coreos:
  units:
    - name: panamax-api.service
      command: start
      content: |
        [Unit]
        Requires=etcd fleet systemd-journal-gatewayd.socket
        After=libswarm.service
        ConditionFileNotEmpty=/run/rudder/subnet.env

        [Service]
        EnvironmentFile=/run/rudder/subnet.env
        ExecStartPre=-/usr/bin/mkdir -p /run/panamax
        ExecStartPre=-/usr/bin/git clone https://github.com/CenturyLinkLabs/panamax-api /opt/panamax-api
        ExecStart=/bin/bash -xc "NODE=$(echo ${RUDDER_SUBNET} | cut -d /) exec /usr/bin/docker run --name panamax-api-build /opt/panamax-api:/var/app/panamax-api -p 8888:3000 -e FLEETCTL_ENDPOINT=http://$NODE:4001 -e JOURNAL_ENDPOINT=http://$NODE:19531 -e DOCKER_HOST=tcp://$NODE:4243 centurylink/panamax-ruby-base /bin/bash -xc 'cd /var/app/panamax-api; bundle ; rake db:create db:migrate db:seed; rake panamax:templates:load ; rails server'"
        RemainAfterExit=yes
    - name: panamax-ui.service
      command: start
      enable: true
      content: |
        [Unit]
        After=panamax-api.service
        ConditionFileNotEmpty=/run/rudder/subnet.env

        [Service]
        EnvironmentFile=/run/rudder/subnet.env
        ExecStart=/bin/bash -xc "NODE=$(echo ${RUDDER_SUBNET} | cut -d /) exec /usr/bin/docker run -e PMX_API_PORT_3000_TCP_ADDR=$NODE -e PMX_API_PORT_3000_TCP_PORT=8888 -d centurylink/panamax-ui
        Restart=on-failure
        TimeoutSec=10
        RestartSec=5
        Type=oneshot
