#cloud-config

coreos:
  units:
    - name: panamax-api.service
      command: start
      content: |
        [Unit]
        Requires=systemd-journal-gatewayd.socket
        After=libswarm.service
        ConditionFileNotEmpty=/run/rudder/subnet.env

        [Service]
        EnvironmentFile=/run/rudder/subnet.env
        ExecStartPre=-/usr/bin/mkdir -p /run/panamax
        ExecStartPre=-/usr/bin/git clone https://github.com/CenturyLinkLabs/panamax-api /opt/panamax-api
        ExecStartPre=-/bin/bash -xc 'echo -n $(echo ${RUDDER_SUBNET} | cut -d/ -f1) > /run/panamax/node'
        ExecStartPre=/usr/bin/docker pull centurylink/panamax-ruby-base
        ExecStart=/bin/bash -xc "exec /usr/bin/docker run --name panamax_api_build -v /opt/panamax-api:/var/app/panamax-api -p 8888:3000 -e FLEETCTL_ENDPOINT=http://$(cat /run/panamax/node):4001 -e JOURNAL_ENDPOINT=http://$(cat /run/panamax/node):19531 -e DOCKER_HOST=tcp://$(cat /run/panamax/node):4243 centurylink/panamax-ruby-base /bin/bash -xc 'cd /var/app/panamax-api; bundle ; rake db:create db:migrate db:seed; rake panamax:templates:load ; exec rails server'"
        RemainAfterExit=yes
    - name: panamax-ui.service
      command: start
      enable: true
      content: |
        [Unit]
        After=panamax-api.service
        ConditionFileNotEmpty=/run/rudder/subnet.env

        [Service]
        EnvironmentFile=/run/rudder/subnet.env
        ExecStartPre=/usr/bin/docker pull centurylink/panamax-ui
        ExecStart=/bin/bash -xc "exec /usr/bin/docker run --name panamax_ui -e PMX_API_PORT_3000_TCP_ADDR=$(echo ${RUDDER_SUBNET} | cut -d/ -f1) -e PMX_API_PORT_3000_TCP_PORT=8888 -d -p 3000:3000 centurylink/panamax-ui"
        Restart=on-failure
        TimeoutSec=10
        RestartSec=5
